name = "MSG Community Edition"
author = "MakeShift Gang, PewPewCricket"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5dc081f4d88e04a5f49efc8fea8e32fdce18cf42931cbe94f43b50b5293eb0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
